import gymnasium as gym
import ale_py
import time
import cv2

gym.register_envs(ale_py)

part1 = []

def a_set(env):
    obs = single_action(env, 3, 30)
    obs = single_action(env, 4, 10)
    obs = single_action(env, 3, 10)
    obs = single_action(env, 2, 25)
    obs = single_action(env, 1, 30)
    obs = single_action(env, 2, 10)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 3, 10)
    obs = single_action(env, 1, 5)
    obs = single_action(env, 3, 10)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 2, 5)
    obs = single_action(env, 3, 8)
    obs = single_action(env, 1, 3)
    obs = single_action(env, 3, 10)
    obs = single_action(env, 4, 3)
    obs = single_action(env, 2, 10)
    obs = single_action(env, 3, 20)
    obs = single_action(env, 1, 5)
    obs = single_action(env, 2, 5)
    obs = single_action(env, 3, 15)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 2, 10)
    obs = single_action(env, 3, 3)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 3, 3)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 2, 10)
    obs = single_action(env, 1, 5)
    obs = single_action(env, 2, 10)
    obs = single_action(env, 4, 10)
    obs = single_action(env, 2, 5)
    obs = single_action(env, 3, 15)
    obs = single_action(env, 4, 8)
    obs = single_action(env, 2, 3)
    obs = single_action(env, 1, 5)
    obs = single_action(env, 3, 20)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 2, 10)
    obs = single_action(env, 3, 3)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 3, 3)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 2, 10)
    obs = single_action(env, 1, 5)
    obs = single_action(env, 2, 10)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 2, 3)
    obs = single_action(env, 1, 50)
    obs = single_action(env, 2, 10)
    obs = single_action(env, 4, 8)
    obs = single_action(env, 3, 6)
    obs = single_action(env, 2, 6)
    obs = single_action(env, 1, 4)
    obs = single_action(env, 2, 10)
    obs = single_action(env, 1, 4)
    obs = single_action(env, 3, 4)
    obs = single_action(env, 2, 15)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 3, 10)
    obs = single_action(env, 2, 3)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 2, 4)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 3, 10)
    obs = single_action(env, 2, 3)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 2, 4)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 3, 10)
    obs = single_action(env, 2, 3)
    obs = single_action(env, 4, 5)
    obs = single_action(env, 3, 10)
    obs = single_action(env, 1, 5)
    obs = single_action(env, 3, 10)
    obs = single_action(env, 2, 5)
    obs = single_action(env, 1, 8)
    obs = single_action(env, 2, 8)
    obs = single_action(env, 3, 10)
    obs = single_action(env, 4, 10)
    obs = single_action(env, 2, 3)
    obs = single_action(env, 3, 15)
    obs = single_action(env, 4, 4)
    obs = single_action(env, 2, 10)

def play_game(env_name, render=True):
    try:
        env = gym.make(env_name, render_mode='human' if render else None)
        obs, info = env.reset(seed=42)
        obs = single_action(env, 3, 30)
        obs = single_action(env, 4, 10)
        obs = single_action(env, 3, 10)
        obs = single_action(env, 2, 25)
        obs = single_action(env, 1, 30)
        obs = single_action(env, 2, 10)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 3, 10)
        obs = single_action(env, 1, 5)
        obs = single_action(env, 3, 10)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 2, 5)
        obs = single_action(env, 3, 8)
        obs = single_action(env, 1, 3)
        obs = single_action(env, 3, 10)
        obs = single_action(env, 4, 3)
        obs = single_action(env, 2, 10)
        obs = single_action(env, 3, 20)
        obs = single_action(env, 1, 5)
        obs = single_action(env, 2, 5)
        obs = single_action(env, 3, 15)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 2, 10)
        obs = single_action(env, 3, 3)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 3, 3)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 2, 10)
        obs = single_action(env, 1, 5)
        obs = single_action(env, 2, 10)
        obs = single_action(env, 4, 10)
        obs = single_action(env, 2, 5)
        obs = single_action(env, 3, 15)
        obs = single_action(env, 4, 8)
        obs = single_action(env, 2, 3)
        obs = single_action(env, 1, 5)
        obs = single_action(env, 3, 20)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 2, 10)
        obs = single_action(env, 3, 3)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 3, 3)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 2, 10)
        obs = single_action(env, 1, 5)
        obs = single_action(env, 2, 10)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 2, 3)
        obs = single_action(env, 1, 50)
        obs = single_action(env, 2, 10)
        obs = single_action(env, 4, 8)
        obs = single_action(env, 3, 6)
        obs = single_action(env, 2, 6)
        obs = single_action(env, 1, 4)
        obs = single_action(env, 2, 10)
        obs = single_action(env, 1, 4)
        obs = single_action(env, 3, 4)
        obs = single_action(env, 2, 15)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 3, 10)
        obs = single_action(env, 2, 3)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 2, 4)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 3, 10)
        obs = single_action(env, 2, 3)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 2, 4)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 3, 10)
        obs = single_action(env, 2, 3)
        obs = single_action(env, 4, 5)
        obs = single_action(env, 3, 10)
        obs = single_action(env, 1, 5)
        obs = single_action(env, 3, 10)
        obs = single_action(env, 2, 5)
        obs = single_action(env, 1, 8)
        obs = single_action(env, 2, 8)
        obs = single_action(env, 3, 10)
        obs = single_action(env, 4, 10)
        obs = single_action(env, 2, 3)
        obs = single_action(env, 3, 15)
        obs = single_action(env, 4, 4)
        obs = single_action(env, 2, 10)

        a_set(env)
        
        env.close()
        
    except Exception as e:
        print(f"错误: {e}")

def single_action(env, action_num, duration):
    for _ in range(duration):
        obs, reward, terminated, truncated, info = env.step(action_num)
        #cv2.imwrite('cut/cut.png', cv2.cvtColor(obs, cv2.COLOR_RGB2BGR))

    #cv2.imwrite('cut/cut.png', cv2.cvtColor(obs, cv2.COLOR_RGB2BGR))
    return obs

play_game('ALE/Pacman-v5', True)

